module: SwiftBeanCountParserUtils
readme: README.md
clean: true
disable_search: true
author: Nef10
author_url: https://github.com/Nef10
root_url: https://Nef10.github.io/SwiftBeanCountParserUtils/
github_url: https://github.com/Nef10/SwiftBeanCountParserUtils
github_file_prefix: https://github.com/Nef10/SwiftBeanCountParserUtils/blob/main
output: ./docs
theme: fullwidth
